package serr_test

import (
	"bytes"
	"strings"
	"testing"

	"github.com/ngicks/go-common/serr"
	"github.com/ngicks/go-common/serr/internal/callstack/baseerr"
	"github.com/ngicks/go-common/serr/internal/callstack/pkg0"
)

//go:generate go run ./internal/generate_test_call

func TestWithStack(t *testing.T) {
	var buf bytes.Buffer

	baseerr.Depth = 0

	buf.Reset()
	err := pkg0.F_0_0()
	errPrinting := serr.PrintStack(&buf, err)
	if errPrinting != nil {
		t.Fatalf("print should success: %v", errPrinting)
	}

	// skip this function, test caller, and the last empty new line.
	expected := exampleStack
	actual := trimLine(buf.String(), 0, -3)
	if expected != actual {
		t.Logf("expected = %s", expected)
		t.Logf("actual = %s", actual)
		t.Fatalf("not correct")
	}

	baseerr.Depth = -1
	buf.Reset()
	err = pkg0.F_0_0()
	_ = serr.PrintStack(&buf, err)
	// first line differs. skipping 1.
	// see "github.com/ngicks/go-common/serr/internal/callstack/baseerr".WrapBase()
	// also skip last line since it is just a newline.
	expected = trimLine(exampleStack, 1, 64)
	actual = trimLine(buf.String(), 1, -1)
	if expected != actual {
		t.Logf("expected = %s", expected)
		t.Logf("actual = %s", actual)
		t.Fatalf("not correct")
	}

	baseerr.Depth = 27
	buf.Reset()
	err = pkg0.F_0_0()
	_ = serr.PrintStack(&buf, err)
	expected = trimLine(exampleStack, 1, 27)
	actual = trimLine(buf.String(), 1, -1)
	if expected != actual {
		t.Logf("expected = %s", expected)
		t.Logf("actual = %s", actual)
		t.Fatalf("not correct")
	}
}

func trimLine(s string, i, j int) string {
	lines := strings.Split(s, "\n")
	if j < 0 {
		j = len(lines) + j
	}
	return strings.Join(lines[i:j], "\n")
}

var (
	exampleStack = `github.com/ngicks/go-common/serr/internal/callstack/baseerr.WrapBase(/git/github.com/ngicks/go-common/serr/internal/callstack/baseerr/err.go:18)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_4_9(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg4/a4.go:44)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_4_8(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg4/a4.go:40)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_4_7(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg4/a4.go:36)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_4_6(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg4/a4.go:32)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_4_5(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg4/a4.go:28)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_4_4(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg4/a4.go:24)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_4_3(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg4/a4.go:20)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_4_2(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg4/a4.go:16)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_4_1(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg4/a4.go:12)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_4_0(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg4/a4.go:8)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_3_9(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg4/a3.go:40)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_3_8(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg4/a3.go:36)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_3_7(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg4/a3.go:32)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_3_6(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg4/a3.go:28)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_3_5(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg4/a3.go:24)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_3_4(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg4/a3.go:20)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_3_3(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg4/a3.go:16)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_3_2(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg4/a3.go:12)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_3_1(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg4/a3.go:8)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_3_0(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg4/a3.go:4)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_2_9(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg4/a2.go:40)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_2_8(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg4/a2.go:36)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_2_7(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg4/a2.go:32)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_2_6(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg4/a2.go:28)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_2_5(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg4/a2.go:24)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_2_4(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg4/a2.go:20)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_2_3(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg4/a2.go:16)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_2_2(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg4/a2.go:12)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_2_1(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg4/a2.go:8)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_2_0(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg4/a2.go:4)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_1_9(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg4/a1.go:40)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_1_8(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg4/a1.go:36)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_1_7(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg4/a1.go:32)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_1_6(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg4/a1.go:28)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_1_5(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg4/a1.go:24)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_1_4(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg4/a1.go:20)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_1_3(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg4/a1.go:16)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_1_2(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg4/a1.go:12)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_1_1(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg4/a1.go:8)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_1_0(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg4/a1.go:4)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_0_9(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg4/a0.go:40)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_0_8(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg4/a0.go:36)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_0_7(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg4/a0.go:32)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_0_6(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg4/a0.go:28)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_0_5(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg4/a0.go:24)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_0_4(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg4/a0.go:20)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_0_3(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg4/a0.go:16)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_0_2(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg4/a0.go:12)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_0_1(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg4/a0.go:8)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_0_0(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg4/a0.go:4)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_4_9(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg3/a4.go:44)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_4_8(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg3/a4.go:40)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_4_7(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg3/a4.go:36)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_4_6(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg3/a4.go:32)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_4_5(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg3/a4.go:28)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_4_4(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg3/a4.go:24)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_4_3(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg3/a4.go:20)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_4_2(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg3/a4.go:16)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_4_1(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg3/a4.go:12)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_4_0(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg3/a4.go:8)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_3_9(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg3/a3.go:40)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_3_8(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg3/a3.go:36)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_3_7(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg3/a3.go:32)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_3_6(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg3/a3.go:28)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_3_5(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg3/a3.go:24)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_3_4(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg3/a3.go:20)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_3_3(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg3/a3.go:16)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_3_2(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg3/a3.go:12)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_3_1(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg3/a3.go:8)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_3_0(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg3/a3.go:4)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_2_9(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg3/a2.go:40)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_2_8(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg3/a2.go:36)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_2_7(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg3/a2.go:32)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_2_6(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg3/a2.go:28)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_2_5(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg3/a2.go:24)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_2_4(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg3/a2.go:20)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_2_3(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg3/a2.go:16)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_2_2(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg3/a2.go:12)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_2_1(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg3/a2.go:8)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_2_0(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg3/a2.go:4)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_1_9(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg3/a1.go:40)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_1_8(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg3/a1.go:36)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_1_7(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg3/a1.go:32)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_1_6(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg3/a1.go:28)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_1_5(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg3/a1.go:24)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_1_4(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg3/a1.go:20)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_1_3(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg3/a1.go:16)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_1_2(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg3/a1.go:12)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_1_1(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg3/a1.go:8)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_1_0(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg3/a1.go:4)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_0_9(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg3/a0.go:40)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_0_8(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg3/a0.go:36)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_0_7(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg3/a0.go:32)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_0_6(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg3/a0.go:28)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_0_5(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg3/a0.go:24)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_0_4(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg3/a0.go:20)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_0_3(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg3/a0.go:16)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_0_2(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg3/a0.go:12)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_0_1(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg3/a0.go:8)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_0_0(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg3/a0.go:4)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_4_9(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg2/a4.go:44)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_4_8(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg2/a4.go:40)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_4_7(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg2/a4.go:36)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_4_6(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg2/a4.go:32)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_4_5(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg2/a4.go:28)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_4_4(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg2/a4.go:24)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_4_3(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg2/a4.go:20)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_4_2(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg2/a4.go:16)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_4_1(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg2/a4.go:12)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_4_0(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg2/a4.go:8)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_3_9(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg2/a3.go:40)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_3_8(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg2/a3.go:36)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_3_7(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg2/a3.go:32)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_3_6(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg2/a3.go:28)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_3_5(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg2/a3.go:24)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_3_4(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg2/a3.go:20)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_3_3(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg2/a3.go:16)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_3_2(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg2/a3.go:12)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_3_1(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg2/a3.go:8)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_3_0(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg2/a3.go:4)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_2_9(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg2/a2.go:40)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_2_8(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg2/a2.go:36)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_2_7(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg2/a2.go:32)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_2_6(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg2/a2.go:28)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_2_5(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg2/a2.go:24)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_2_4(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg2/a2.go:20)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_2_3(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg2/a2.go:16)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_2_2(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg2/a2.go:12)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_2_1(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg2/a2.go:8)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_2_0(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg2/a2.go:4)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_1_9(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg2/a1.go:40)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_1_8(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg2/a1.go:36)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_1_7(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg2/a1.go:32)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_1_6(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg2/a1.go:28)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_1_5(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg2/a1.go:24)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_1_4(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg2/a1.go:20)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_1_3(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg2/a1.go:16)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_1_2(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg2/a1.go:12)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_1_1(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg2/a1.go:8)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_1_0(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg2/a1.go:4)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_0_9(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg2/a0.go:40)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_0_8(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg2/a0.go:36)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_0_7(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg2/a0.go:32)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_0_6(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg2/a0.go:28)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_0_5(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg2/a0.go:24)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_0_4(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg2/a0.go:20)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_0_3(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg2/a0.go:16)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_0_2(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg2/a0.go:12)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_0_1(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg2/a0.go:8)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_0_0(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg2/a0.go:4)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_4_9(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg1/a4.go:44)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_4_8(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg1/a4.go:40)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_4_7(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg1/a4.go:36)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_4_6(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg1/a4.go:32)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_4_5(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg1/a4.go:28)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_4_4(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg1/a4.go:24)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_4_3(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg1/a4.go:20)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_4_2(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg1/a4.go:16)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_4_1(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg1/a4.go:12)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_4_0(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg1/a4.go:8)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_3_9(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg1/a3.go:40)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_3_8(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg1/a3.go:36)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_3_7(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg1/a3.go:32)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_3_6(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg1/a3.go:28)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_3_5(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg1/a3.go:24)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_3_4(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg1/a3.go:20)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_3_3(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg1/a3.go:16)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_3_2(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg1/a3.go:12)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_3_1(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg1/a3.go:8)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_3_0(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg1/a3.go:4)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_2_9(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg1/a2.go:40)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_2_8(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg1/a2.go:36)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_2_7(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg1/a2.go:32)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_2_6(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg1/a2.go:28)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_2_5(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg1/a2.go:24)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_2_4(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg1/a2.go:20)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_2_3(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg1/a2.go:16)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_2_2(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg1/a2.go:12)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_2_1(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg1/a2.go:8)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_2_0(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg1/a2.go:4)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_1_9(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg1/a1.go:40)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_1_8(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg1/a1.go:36)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_1_7(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg1/a1.go:32)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_1_6(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg1/a1.go:28)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_1_5(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg1/a1.go:24)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_1_4(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg1/a1.go:20)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_1_3(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg1/a1.go:16)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_1_2(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg1/a1.go:12)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_1_1(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg1/a1.go:8)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_1_0(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg1/a1.go:4)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_0_9(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg1/a0.go:40)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_0_8(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg1/a0.go:36)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_0_7(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg1/a0.go:32)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_0_6(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg1/a0.go:28)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_0_5(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg1/a0.go:24)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_0_4(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg1/a0.go:20)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_0_3(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg1/a0.go:16)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_0_2(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg1/a0.go:12)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_0_1(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg1/a0.go:8)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_0_0(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg1/a0.go:4)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_4_9(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg0/a4.go:44)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_4_8(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg0/a4.go:40)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_4_7(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg0/a4.go:36)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_4_6(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg0/a4.go:32)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_4_5(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg0/a4.go:28)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_4_4(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg0/a4.go:24)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_4_3(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg0/a4.go:20)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_4_2(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg0/a4.go:16)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_4_1(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg0/a4.go:12)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_4_0(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg0/a4.go:8)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_3_9(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg0/a3.go:40)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_3_8(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg0/a3.go:36)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_3_7(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg0/a3.go:32)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_3_6(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg0/a3.go:28)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_3_5(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg0/a3.go:24)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_3_4(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg0/a3.go:20)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_3_3(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg0/a3.go:16)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_3_2(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg0/a3.go:12)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_3_1(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg0/a3.go:8)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_3_0(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg0/a3.go:4)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_2_9(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg0/a2.go:40)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_2_8(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg0/a2.go:36)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_2_7(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg0/a2.go:32)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_2_6(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg0/a2.go:28)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_2_5(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg0/a2.go:24)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_2_4(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg0/a2.go:20)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_2_3(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg0/a2.go:16)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_2_2(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg0/a2.go:12)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_2_1(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg0/a2.go:8)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_2_0(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg0/a2.go:4)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_1_9(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg0/a1.go:40)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_1_8(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg0/a1.go:36)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_1_7(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg0/a1.go:32)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_1_6(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg0/a1.go:28)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_1_5(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg0/a1.go:24)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_1_4(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg0/a1.go:20)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_1_3(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg0/a1.go:16)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_1_2(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg0/a1.go:12)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_1_1(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg0/a1.go:8)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_1_0(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg0/a1.go:4)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_0_9(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg0/a0.go:40)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_0_8(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg0/a0.go:36)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_0_7(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg0/a0.go:32)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_0_6(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg0/a0.go:28)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_0_5(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg0/a0.go:24)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_0_4(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg0/a0.go:20)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_0_3(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg0/a0.go:16)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_0_2(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg0/a0.go:12)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_0_1(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg0/a0.go:8)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_0_0(/git/github.com/ngicks/go-common/serr/internal/callstack/pkg0/a0.go:4)`
)
