package serr_test

import (
	"fmt"
	"path"
	"strings"
	"testing"

	"github.com/ngicks/go-common/serr"
	"github.com/ngicks/go-common/serr/internal/callstack/baseerr"
	"github.com/ngicks/go-common/serr/internal/callstack/pkg0"
)

//go:generate go run ./internal/generate_test_call

func TestWithStack(t *testing.T) {
	defer func() {
		opt := *baseerr.DefaultOpt
		baseerr.Opt = &opt
	}()

	opt := *baseerr.DefaultOpt
	baseerr.Opt = &opt
	err := pkg0.F_0_0()
	// skip this function, test caller, and the last empty new line.
	expected := exampleStack
	actual := trimLine(printStack(err), 0, -3)
	if expected != actual {
		t.Logf("expected = %s", expected)
		t.Logf("actual = %s", actual)
		t.Fatalf("not correct")
	}

	baseerr.Opt = nil
	err = pkg0.F_0_0()
	// first line differs. skipping 1.
	// see "github.com/ngicks/go-common/serr/internal/callstack/baseerr".WrapBase()
	// also skip last line since it is just a newline.
	expected = trimLine(exampleStack, 1, 64)
	actual = trimLine(printStack(err), 1, -1)
	if expected != actual {
		t.Logf("expected = %s", expected)
		t.Logf("actual = %s", actual)
		t.Fatalf("not correct")
	}

	baseerr.Opt = &serr.WrapStackOpt{Depth: 27}
	err = pkg0.F_0_0()
	expected = trimLine(exampleStack, 1, 27)
	actual = trimLine(printStack(err), 1, -1)
	if expected != actual {
		t.Logf("expected = %s", expected)
		t.Logf("actual = %s", actual)
		t.Fatalf("not correct")
	}

	baseerr.Opt = &serr.WrapStackOpt{Skip: 1}
	err = pkg0.F_0_0()
	expected = "github.com/ngicks/go-common/serr.wrapStack"
	actual = firstLine(printStack(err))
	if !strings.HasPrefix(actual, expected) {
		t.Logf("expected = %s", expected)
		t.Logf("actual = %s", actual)
		t.Fatalf("not correct: expecting expected is prefix of actual")
	}

	// fallen back to 3.
	baseerr.Opt = &serr.WrapStackOpt{Skip: 0}
	err = pkg0.F_0_0()
	expected = "github.com/ngicks/go-common/serr/internal/callstack/baseerr.WrapBase"
	actual = firstLine(printStack(err))
	if !strings.HasPrefix(actual, expected) {
		t.Logf("expected = %s", expected)
		t.Logf("actual = %s", actual)
		t.Fatalf("not correct: expecting expected is prefix of actual")
	}
}

func printStack(err error) string {
	s := strings.Builder{}
	for f := range serr.Frames(err) {
		// print only base name for stability, in case -trimpath option is passed.
		_, _ = fmt.Fprintf(&s, "%s(%s:%d)\n", f.Function, path.Base(f.File), f.Line)
	}
	return s.String()
}

func trimLine(s string, i, j int) string {
	lines := strings.Split(s, "\n")
	if j <= 0 {
		j = len(lines) + j
	}
	return strings.Join(lines[i:j], "\n")
}
func firstLine(s string) string {
	lines := strings.Split(s, "\n")
	if len(lines) > 0 {
		return lines[0]
	}
	return ""
}

var (
	exampleStack = `github.com/ngicks/go-common/serr/internal/callstack/baseerr.WrapBase(err.go:11)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_4_9(a4.go:44)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_4_8(a4.go:40)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_4_7(a4.go:36)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_4_6(a4.go:32)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_4_5(a4.go:28)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_4_4(a4.go:24)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_4_3(a4.go:20)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_4_2(a4.go:16)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_4_1(a4.go:12)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_4_0(a4.go:8)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_3_9(a3.go:40)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_3_8(a3.go:36)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_3_7(a3.go:32)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_3_6(a3.go:28)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_3_5(a3.go:24)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_3_4(a3.go:20)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_3_3(a3.go:16)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_3_2(a3.go:12)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_3_1(a3.go:8)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_3_0(a3.go:4)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_2_9(a2.go:40)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_2_8(a2.go:36)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_2_7(a2.go:32)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_2_6(a2.go:28)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_2_5(a2.go:24)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_2_4(a2.go:20)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_2_3(a2.go:16)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_2_2(a2.go:12)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_2_1(a2.go:8)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_2_0(a2.go:4)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_1_9(a1.go:40)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_1_8(a1.go:36)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_1_7(a1.go:32)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_1_6(a1.go:28)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_1_5(a1.go:24)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_1_4(a1.go:20)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_1_3(a1.go:16)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_1_2(a1.go:12)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_1_1(a1.go:8)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_1_0(a1.go:4)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_0_9(a0.go:40)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_0_8(a0.go:36)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_0_7(a0.go:32)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_0_6(a0.go:28)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_0_5(a0.go:24)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_0_4(a0.go:20)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_0_3(a0.go:16)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_0_2(a0.go:12)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_0_1(a0.go:8)
github.com/ngicks/go-common/serr/internal/callstack/pkg4.F_0_0(a0.go:4)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_4_9(a4.go:44)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_4_8(a4.go:40)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_4_7(a4.go:36)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_4_6(a4.go:32)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_4_5(a4.go:28)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_4_4(a4.go:24)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_4_3(a4.go:20)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_4_2(a4.go:16)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_4_1(a4.go:12)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_4_0(a4.go:8)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_3_9(a3.go:40)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_3_8(a3.go:36)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_3_7(a3.go:32)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_3_6(a3.go:28)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_3_5(a3.go:24)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_3_4(a3.go:20)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_3_3(a3.go:16)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_3_2(a3.go:12)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_3_1(a3.go:8)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_3_0(a3.go:4)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_2_9(a2.go:40)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_2_8(a2.go:36)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_2_7(a2.go:32)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_2_6(a2.go:28)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_2_5(a2.go:24)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_2_4(a2.go:20)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_2_3(a2.go:16)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_2_2(a2.go:12)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_2_1(a2.go:8)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_2_0(a2.go:4)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_1_9(a1.go:40)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_1_8(a1.go:36)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_1_7(a1.go:32)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_1_6(a1.go:28)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_1_5(a1.go:24)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_1_4(a1.go:20)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_1_3(a1.go:16)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_1_2(a1.go:12)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_1_1(a1.go:8)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_1_0(a1.go:4)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_0_9(a0.go:40)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_0_8(a0.go:36)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_0_7(a0.go:32)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_0_6(a0.go:28)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_0_5(a0.go:24)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_0_4(a0.go:20)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_0_3(a0.go:16)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_0_2(a0.go:12)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_0_1(a0.go:8)
github.com/ngicks/go-common/serr/internal/callstack/pkg3.F_0_0(a0.go:4)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_4_9(a4.go:44)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_4_8(a4.go:40)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_4_7(a4.go:36)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_4_6(a4.go:32)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_4_5(a4.go:28)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_4_4(a4.go:24)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_4_3(a4.go:20)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_4_2(a4.go:16)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_4_1(a4.go:12)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_4_0(a4.go:8)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_3_9(a3.go:40)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_3_8(a3.go:36)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_3_7(a3.go:32)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_3_6(a3.go:28)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_3_5(a3.go:24)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_3_4(a3.go:20)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_3_3(a3.go:16)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_3_2(a3.go:12)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_3_1(a3.go:8)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_3_0(a3.go:4)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_2_9(a2.go:40)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_2_8(a2.go:36)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_2_7(a2.go:32)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_2_6(a2.go:28)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_2_5(a2.go:24)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_2_4(a2.go:20)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_2_3(a2.go:16)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_2_2(a2.go:12)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_2_1(a2.go:8)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_2_0(a2.go:4)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_1_9(a1.go:40)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_1_8(a1.go:36)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_1_7(a1.go:32)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_1_6(a1.go:28)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_1_5(a1.go:24)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_1_4(a1.go:20)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_1_3(a1.go:16)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_1_2(a1.go:12)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_1_1(a1.go:8)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_1_0(a1.go:4)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_0_9(a0.go:40)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_0_8(a0.go:36)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_0_7(a0.go:32)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_0_6(a0.go:28)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_0_5(a0.go:24)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_0_4(a0.go:20)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_0_3(a0.go:16)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_0_2(a0.go:12)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_0_1(a0.go:8)
github.com/ngicks/go-common/serr/internal/callstack/pkg2.F_0_0(a0.go:4)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_4_9(a4.go:44)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_4_8(a4.go:40)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_4_7(a4.go:36)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_4_6(a4.go:32)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_4_5(a4.go:28)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_4_4(a4.go:24)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_4_3(a4.go:20)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_4_2(a4.go:16)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_4_1(a4.go:12)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_4_0(a4.go:8)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_3_9(a3.go:40)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_3_8(a3.go:36)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_3_7(a3.go:32)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_3_6(a3.go:28)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_3_5(a3.go:24)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_3_4(a3.go:20)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_3_3(a3.go:16)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_3_2(a3.go:12)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_3_1(a3.go:8)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_3_0(a3.go:4)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_2_9(a2.go:40)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_2_8(a2.go:36)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_2_7(a2.go:32)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_2_6(a2.go:28)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_2_5(a2.go:24)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_2_4(a2.go:20)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_2_3(a2.go:16)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_2_2(a2.go:12)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_2_1(a2.go:8)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_2_0(a2.go:4)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_1_9(a1.go:40)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_1_8(a1.go:36)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_1_7(a1.go:32)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_1_6(a1.go:28)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_1_5(a1.go:24)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_1_4(a1.go:20)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_1_3(a1.go:16)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_1_2(a1.go:12)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_1_1(a1.go:8)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_1_0(a1.go:4)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_0_9(a0.go:40)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_0_8(a0.go:36)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_0_7(a0.go:32)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_0_6(a0.go:28)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_0_5(a0.go:24)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_0_4(a0.go:20)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_0_3(a0.go:16)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_0_2(a0.go:12)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_0_1(a0.go:8)
github.com/ngicks/go-common/serr/internal/callstack/pkg1.F_0_0(a0.go:4)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_4_9(a4.go:44)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_4_8(a4.go:40)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_4_7(a4.go:36)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_4_6(a4.go:32)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_4_5(a4.go:28)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_4_4(a4.go:24)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_4_3(a4.go:20)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_4_2(a4.go:16)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_4_1(a4.go:12)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_4_0(a4.go:8)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_3_9(a3.go:40)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_3_8(a3.go:36)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_3_7(a3.go:32)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_3_6(a3.go:28)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_3_5(a3.go:24)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_3_4(a3.go:20)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_3_3(a3.go:16)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_3_2(a3.go:12)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_3_1(a3.go:8)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_3_0(a3.go:4)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_2_9(a2.go:40)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_2_8(a2.go:36)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_2_7(a2.go:32)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_2_6(a2.go:28)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_2_5(a2.go:24)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_2_4(a2.go:20)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_2_3(a2.go:16)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_2_2(a2.go:12)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_2_1(a2.go:8)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_2_0(a2.go:4)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_1_9(a1.go:40)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_1_8(a1.go:36)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_1_7(a1.go:32)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_1_6(a1.go:28)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_1_5(a1.go:24)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_1_4(a1.go:20)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_1_3(a1.go:16)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_1_2(a1.go:12)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_1_1(a1.go:8)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_1_0(a1.go:4)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_0_9(a0.go:40)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_0_8(a0.go:36)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_0_7(a0.go:32)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_0_6(a0.go:28)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_0_5(a0.go:24)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_0_4(a0.go:20)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_0_3(a0.go:16)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_0_2(a0.go:12)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_0_1(a0.go:8)
github.com/ngicks/go-common/serr/internal/callstack/pkg0.F_0_0(a0.go:4)`
)
