// Code generated by github.com/ngicks/go-common/contextkey/generate DO NOT EDIT
package contextkey

import (
	"context"

)

var (
	KeyRequestId = keyTypeFunc("string")
)

// WithRequestId returns a copy of parent in which the value associated with KeyRequestId is v.
// v associated with contexts for KeyRequestId can later be retrieved by any of Value method,
// ValueRequestId, ValueRequestIdFallback or ValueRequestIdDefault.
func WithRequestId(ctx context.Context, v string) context.Context {
	return context.WithValue(ctx, KeyRequestId, v)
}

// ValueRequestId returns string associated with ctx for KeyRequestId.
// ok is false if the value was not associated or other than string.
func ValueRequestId(ctx context.Context) (v string, ok bool) {
	val := ctx.Value(KeyRequestId)
	if v, ok := val.(string); ok {
		return v, true
	}
	var zero string
	return zero, false
}

// ValueRequestIdFallback returns string associated with ctx for KeyRequestId,
// or in case the value was not associated to ctx, returns fallback.
func ValueRequestIdFallback(ctx context.Context, fallback string) string {
	v, ok := ValueRequestId(ctx)
	if ok {
		return v
	}
	return fallback
}

// ValueRequestIdFallbackFn returns string associated with ctx for KeyRequestId,
// or in case the value was not associated to ctx, returns calling result of fallbackFn.
func ValueRequestIdFallbackFn(ctx context.Context, fallbackFn func() string) string {
	v, ok := ValueRequestId(ctx)
	if ok {
		return v
	}
	return fallbackFn()
}

// ValueRequestIdDefault returns string associated with ctx for KeyRequestId.
// In case the value was not associated, returns default value for the type.
//
// The default value is an evaluation result of "".
func ValueRequestIdDefault(ctx context.Context) string {
	return ValueRequestIdFallbackFn(ctx, func () string { return "" })
}
