// Code generated by github.com/ngicks/go-common/contextkey/generate DO NOT EDIT
package contextkey

import (
	"context"
	"testing"
	"os"
)

func TestSignalChan(t *testing.T) {
	var zero chan os.Signal

	ctx := context.Background()

	if v := ctx.Value(KeySignalChan); v != nil {
		t.Fatalf("there is value for key %v", KeySignalChan)
	}

	noDefaultValue := func() chan os.Signal { return make(chan os.Signal, 10) }() 
	ctx = WithSignalChan(ctx, noDefaultValue)

	v1 := ctx.Value(KeySignalChan)
	if v1 == nil {
		t.Fatalf("no value for key %v", KeySignalChan)
	}
	if _, ok := v1.(chan os.Signal); !ok {
		t.Fatalf("different type associated, want = %s, got = %T", "chan os.Signal", v1)
	}

	getAndCompare := func(eq bool) func(v2 chan os.Signal, ok bool) {
		return func(v2 chan os.Signal, ok bool) {
			t.Helper()
			not := "not "
			if eq {
				not = ""
			}
			if ok != eq {
				t.Fatalf("different type associated, want = %s%s, got = %T", not, "chan os.Signal", v1)
			}

			if func (v1, v2 any) bool { return v1 == v2 }(v1, v2) != eq {
				t.Fatalf("wrong value retrieved, want = %s%v, got = %v", not, v1, v2)
			}
		}
	}

	getAndCompare(true)(ValueSignalChan(ctx))
	getAndCompare(true)(ValueSignalChanFallback(ctx, zero), true)
	getAndCompare(true)(ValueSignalChanFallbackFn(ctx, func() chan os.Signal { return zero }), true)
	getAndCompare(true)(ValueSignalChanDefault(ctx), true)

	ctx = context.WithValue(ctx, KeySignalChan, struct{}{})
	getAndCompare(false)(ValueSignalChan(ctx))
	getAndCompare(false)(ValueSignalChanFallback(ctx, zero), false)
	getAndCompare(false)(ValueSignalChanFallbackFn(ctx, func() chan os.Signal { return zero }), false)
	getAndCompare(false)(ValueSignalChanDefault(ctx), false)

	ctx = context.Background()
	getAndCompare(false)(ValueSignalChan(ctx))
	getAndCompare(false)(ValueSignalChanFallback(ctx, zero), false)
	getAndCompare(false)(ValueSignalChanFallbackFn(ctx, func() chan os.Signal { return zero }), false)
	getAndCompare(false)(ValueSignalChanDefault(ctx), false)

	if v := ValueSignalChanFallback(ctx, noDefaultValue); !func (v1, v2 any) bool { return v1 == v2 }(v, noDefaultValue) {
		t.Fatalf("ValueSignalChanFallback did not fall back correctly. want = %v, got = %v", noDefaultValue, v)
	}
	if v := ValueSignalChanFallbackFn(ctx, func() chan os.Signal { return noDefaultValue }); !func (v1, v2 any) bool { return v1 == v2 }(v, noDefaultValue) {
		t.Fatalf("ValueSignalChanFallbackFn did not fall back correctly. want = %v, got = %v", noDefaultValue, v)
	}

	v := ValueSignalChanDefault(ctx)
	if !func (v1, v2 any) bool { return v1 == v2 }(v, (chan os.Signal)(nil)) {
		def1, def2 := (chan os.Signal)(nil), (chan os.Signal)(nil)
		if  !func (v1, v2 any) bool { return v1 == v2 }(def1, def2) {
			t.Logf("default value is non-deterministic; You must implement your own test for ValueSignalChanDefault(ctx)")
		} else {
			t.Fatalf("ValueSignalChanDefault did not fall back to default value")
		}
	}
}