// Code generated by github.com/ngicks/go-common/contextkey/generate DO NOT EDIT
package contextkey

import (
	"context"
	"os"
)

var (
	KeySignalChan = keyTypeFunc("chan os.Signal")
)

// WithSignalChan returns a copy of parent in which the value associated with KeySignalChan is v.
// v associated with contexts for KeySignalChan can later be retrieved by any of Value method,
// ValueSignalChan, ValueSignalChanFallback or ValueSignalChanDefault.
func WithSignalChan(ctx context.Context, v chan os.Signal) context.Context {
	return context.WithValue(ctx, KeySignalChan, v)
}

// ValueSignalChan returns chan os.Signal associated with ctx for KeySignalChan.
// ok is false if the value was not associated or other than chan os.Signal.
func ValueSignalChan(ctx context.Context) (v chan os.Signal, ok bool) {
	val := ctx.Value(KeySignalChan)
	if v, ok := val.(chan os.Signal); ok {
		return v, true
	}
	var zero chan os.Signal
	return zero, false
}

// ValueSignalChanFallback returns chan os.Signal associated with ctx for KeySignalChan,
// or in case the value was not associated to ctx, returns fallback.
func ValueSignalChanFallback(ctx context.Context, fallback chan os.Signal) chan os.Signal {
	v, ok := ValueSignalChan(ctx)
	if ok {
		return v
	}
	return fallback
}

// ValueSignalChanFallbackFn returns chan os.Signal associated with ctx for KeySignalChan,
// or in case the value was not associated to ctx, returns calling result of fallbackFn.
func ValueSignalChanFallbackFn(ctx context.Context, fallbackFn func() chan os.Signal) chan os.Signal {
	v, ok := ValueSignalChan(ctx)
	if ok {
		return v
	}
	return fallbackFn()
}

// ValueSignalChanDefault returns chan os.Signal associated with ctx for KeySignalChan.
// In case the value was not associated, returns default value for the type.
//
// The default value is an evaluation result of (chan os.Signal)(nil).
func ValueSignalChanDefault(ctx context.Context) chan os.Signal {
	return ValueSignalChanFallbackFn(ctx, func () chan os.Signal { return (chan os.Signal)(nil) })
}
